env:
  browser: false
  es6: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules:
  arrow-parens: off
